### ISSUE TITLE
Global Stats Tracker

### ISSUE THREAD

**Issue by RyanMalt** [zachadel/GenomeEvolution#60]
Create a global/Autoload stats tracker for the various actions in the game

- [x] Create Stats.gd and add to Autoload
- [x] Connect to death screen
- [x] Track tiles moved
- [x] Track times resources acquired/eaten
- [x] Track number of damaged genes repaired using fix damaged genes with no errors
- [x] Track number of damaged genes repaired using fix damaged genes with errors
- [x] Track number of breaks repaired using join ends with no errors
- [x] Track number of breaks repaired using join ends with errors
- [x] Track number of breaks repaired using copy-repair with no errors
- [x] Track number of breaks repaired using copy repair with errors
- [x] Track number of tiles copied using the copy-repair function
- [x] Track number of genes copied using the copy-repair function
- [x] Track number of tile corrected during copy repair 
- [x] Track number of breaks repaired using collapse duplicates function
- [x] Track number of tiles removed using collapse duplicates function
- [x] Track the number of major upgrades received by genes
- [x] Track the number of minor upgrades received by genes
- [x] Track the number of major downgrades received by genes
- [x] Track the number of minor downgrades received by genes
- [x] Track the number of major upgrades received by blank tiles, resulting in a new gene
- [x] Track the number of skills learned by genes
- [x] Track the maximum value earned by each gene category
- [x] Track the final value earned for each gene category end
- [x] Track the maximum number of transposon tiles
- [x] Track the final number of transposon tiles at game end
- [x] Track the maximum number of blank tiles
- [x] Track the final number of blank tiles at game end 
- [x] Track number of progeny and number of times reproduced
- [x] Track energy spent/resources acquired/resources converted?
- [x] Track the number of genes that become pseudogenes
- [x] Track the number of skills lost by genes
- [x] Track the number of tiles trimmed from breaks
- [x] Track the number of transposons that fuse with genes
- [x] Track the number of genes split by transposons
- [x] Track the number of inversions that occur during repair
- [x] Track the number of tiles that get inverted during repair
- [x] Track the number of "Classic" TEs at present time
- [x] Track the maximum number of "Classic" TEs at any time
- [x] Track the number of "Super Jumper" TEs at present time
- [x] Track the maximum number of "Super Jumper" TEs at any time
- [x] Track the number of "Assist" TEs at present time
- [x] Track the maximum number of "Assist" TEs at any time
- [x] Track the number of "Buddy" TEs at present time
- [x] Track the maximum number of "Buddy" TEs at any time
- [x] Track the number of "Nestler" TEs at present time
- [x] Track the maximum number of "Nestler" TEs at any time
- [x] Track the number of "Commuter" TEs at present time
- [x] Track the maximum number of "Commuter" TEs at any time
- [x] Track the number of "Zigzag" TEs at present time
- [x] Track the maximum number of "Zigzag" TEs at any time
- [x] Track the number of "Buncher" TEs at present time
- [x] Track the maximum number of "Buncher" TEs at any time
